"""is bot col

Revision ID: 002a371b0c6b
Revises: 4b7d23b3e359
Create Date: 2025-11-24 16:35:09.741715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '002a371b0c6b'
down_revision: Union[str, Sequence[str], None] = '4b7d23b3e359'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clicks', sa.Column('is_bot', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clicks', 'is_bot')
    # ### end Alembic commands ###
