"""Initial tables

Revision ID: 4b7d23b3e359
Revises: 
Create Date: 2025-11-24 11:33:21.181311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b7d23b3e359'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('short_urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_code', sa.String(), nullable=True),
    sa.Column('original_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('custom_alias', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('custom_alias')
    )
    op.create_index(op.f('ix_short_urls_id'), 'short_urls', ['id'], unique=False)
    op.create_index(op.f('ix_short_urls_short_code'), 'short_urls', ['short_code'], unique=True)
    op.create_table('clicks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_url_id', sa.Integer(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['short_url_id'], ['short_urls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clicks')
    op.drop_index(op.f('ix_short_urls_short_code'), table_name='short_urls')
    op.drop_index(op.f('ix_short_urls_id'), table_name='short_urls')
    op.drop_table('short_urls')
    # ### end Alembic commands ###
