"""AB testing

Revision ID: ff549a84c3a6
Revises: 002a371b0c6b
Create Date: 2025-11-24 16:55:38.610571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff549a84c3a6'
down_revision: Union[str, Sequence[str], None] = '002a371b0c6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clicks', sa.Column('chosen_url', sa.String(), nullable=True))
    op.add_column('short_urls', sa.Column('secondary_url', sa.String(), nullable=True))
    op.add_column('short_urls', sa.Column('split_percent', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('short_urls', 'split_percent')
    op.drop_column('short_urls', 'secondary_url')
    op.drop_column('clicks', 'chosen_url')
    # ### end Alembic commands ###
